# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#id2
# https://github.com/jupyter-book/jupyter-book/blob/main/.readthedocs.yaml
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    nodejs: "24"
    python: "3.14"
  jobs:
    build:
      html:
        - pip install -r requirements.txt
        - mkdir -p $READTHEDOCS_OUTPUT/html/
        - make html
        - cp -a pages/_build/html/. "$READTHEDOCS_OUTPUT/html"
