# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#id2
# https://github.com/jupyter-book/jupyter-book/blob/main/.readthedocs.yaml
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    nodejs: "24"
    python: "3.14"
  jobs:
    build:
      html:
        # https://github.com/jupyter-book/jb1-redirect-generator?tab=readme-ov-file#prerequisites
        - pip install -r requirements.txt pyyaml click
        - mkdir -p $READTHEDOCS_OUTPUT/html/
        - jupyter book build --html
        # create redirects from old URL structure
        - wget https://raw.githubusercontent.com/jupyter-book/jb1-redirect-generator/main/generate_redirects.py
        - python generate_redirects.py --base-url https://computing-in-context.afeld.me/
        - cp -a _build/html/. "$READTHEDOCS_OUTPUT/html" && rm -r _build
