name: computing-in-context
channels:
  - default
  - conda-forge
dependencies:
  - ipykernel
  - jupyter-book=1.*
  - jupyterlab
  - lxml
  - nb_conda_kernels
  - nbconvert
  - nbdime
  - nbformat
  - nbmerge
  - openpyxl
  - pandas
  # https://plotly.com/python/mapbox-to-maplibre/
  - plotly>=5.24.0
  # https://github.com/pydata/pydata-sphinx-theme/issues/2067
  - pydata-sphinx-theme<0.16.0
  - pytest
  - requests
  - ruff
  # https://github.com/sphinx-doc/sphinx/issues/10440#issuecomment-1556180835
  - sphinx>=6.2.0
  - statsmodels
  # https://pandas.pydata.org/docs/user_guide/io.html#excel-files
  - xlrd
